# .github/workflows/build-ios-unsigned.yml
name: Build iOS (Unsigned)

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Get commit SHA
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build
        run: xcodebuild -scheme "Real Debrid" -configuration Release archive -archivePath "build/Real Debrid.xcarchive" CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        env:
          IS_NIGHTLY: YES
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r "build/Real Debrid.xcarchive/Products/Applications/Real Debrid.app" Payload
          zip -r Real-Debrid-${{ env.sha_short }}.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Real-Debrid-${{ env.sha_short }}.ipa
          path: Real-Debrid-${{ env.sha_short }}.ipa
          if-no-files-found: error
